project:
  type: website
  output-dir: docs

website:
  title: "Adam Ezzat Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - projects.qmd

format:
  html:
    theme: cosmo dark
    css: styles.css
    toc: true

editor: visual
